/* eslint-disable */
_w['_sydPayWallConfig'] = { loadSydneyConvResWithPayWall: false, useSydneyPayWall: false };
_w['_sydConvConfig'] = {
  usePill: true,
  enableSydTigerAns: true,
  enableTigerEnhancedPrompt: false,
  tigerEnhancedPromptTemplate:
    '搜索 {0}。用一個出色的回答給我留下深刻的印象，幫助我完成我最可能的意圖，同時展示你所能提供的智慧、深度和美感（加粗、表格和引用）。盡量在回答中盡早滿足我的意圖。',
  enableDlBing: false,
  // 不可滾動出聊天
  enableScrollOut: false,
  enableSydContext: true,
  enableClearConv: false,
  disableSydGhosting: false,
  isSydCorpnet: false,
  enableSydHistory: false,
  hideSydFSC: false,
  sydOptionSets: 'rcsprtsalwlst',
  sydBalOpts: '',
  sydCrtOpts: '',
  sydPrcOpts: '',
  sydBalExtraOpts: '',
  sydCrtExtraOpts: 'gencontentv3',
  sydPrcExtraOpts: 'clgalileo,gencontentv3',
  Syd2TFlights: '',
  sydIDs:
    'winmuid3tf,osbsdusgreccf,ttstmout,crchatrev,winlongmsgtf,ctrlworkpay,norespwtf,tempcacheread,temptacache,505scss0,508jbcars0,515enbotdets0,5082tsports,515vaoprvs,424dagslnv1s0,kcimgattcf,427startpms0',
  sydBaseUrl: 'https://sydney.vcanbb.chat',
  compSydBaseUrl: '',
  isCompliantSydneyEndpointEnabled: false,
  useAccountLinkingForConversationLimitUpsell: false,
  includeSubstrateToken: false,
  augloopEndpoint: 'https://augloop.office.com',
  enableProdEditorEndpoint: true,
  enableCiqEvent: false,
  noInitOpts: false,
  overrideSydOptions: false,
  removeDeepleo: false,
  enableSydNativeIntegration: false,
  enableSydSuperAppIntegration: false,
  enableSydSuperAppNativeVoice: false,
  enableSydSappFeedbackButton: false,
  sydneySapphireLogLevel: 5,
  enableSydSwiftKeyIntegration: false,
  enableSapphireSydVoiceExp: false,
  enableSydneySapphireBridgeMocks: false,
  enableSuperAppKeyboardPopup: false,
  sydneySuperAppFeatures: '',
  getLocationDataFromHeader: '',
  sydneySwiftKeyFeatures: '',
  isSappMobileOptimizedOn: false,
  enableSapphireContextRegistration: false,
  enableEdgeMobileNativeTTS: false,
  enableSydPreloadAudioTTS: false,
  enableSydneyShareLink: false,
  sydUrlPart: '',
  compSydUrlPart: '',
  compliantSydOptionsSets: '',
  country: 'United States',
  countryConfidence: 8,
  state: 'California',
  city: 'Los Angeles',
  cityConfidence: 0,
  zip: '',
  timezoneoffset: '8',
  dma: 0,
  lat: '34.0536909',
  long: '-118.242766',
  language: 'Chinese (China)',
  isVisualParityRun: false,
  enableSydAjax: false,
  moveOnlySydXAnswers: true,
  enable1TCibSlot: false,
  enableSydOverlay: false,
  enableSydX1T: true,
  enableSydTestCache: false,
  hideSydMic: false,
  enableSydCarousel: true,
  fromNoResults: false,
  sydTestCacheMsg: '',
  traceId: '646ae52b797848988e6618d6205cf436',
  extraSappOptions: '',
  extraEdgeOptions: '',
  enableSydMic: false,
  carouselQueries: '',
  sydCarPropQuery: false,
  enableSydShare: true,
  enableTigerCachedAttr: false,
  enableSydCarouselHistory: false,
  enableSydCookLoc: true,
  enableSQMsg: true,
  enable161Feats: true,
  addDv3Opt: true,
  addGenContentv3Opt: false,
  hideSydReconnect: false,
  enableErrorTelemetry: true,
  enableSemSerpNoCache: false,
  checkCreatorAnsFor1T: true,
  enableSydStrictRedirect: false,
  enableAnsCardSuffix: true,
  enableSydStaticAdsLink: false,
  removeDSAT: true,
  enableShortOpt: false,
  enableSpeechExperimentalFeatures: false,
  enableSydAjaxReset: true,
  enableSydCLOC: true,
  enableCdxFeats: true,
  cdxFeats: '',
  enableSecureUpdateConversation: false,
  enableSecureSendFeedback: false,
  disableSecureUpdateConversation: false,
  disableSecureSendFeedback: false,
  enableSemSerpShare: true,
  enableShareModalDialog: true,
  enableFdbkFinalized: true,
  enableRotateDisclaimer: false,
  enableRotateWelMsg: false,
  enableDM: false,
  enableSydImageCreate: true,
  disableCibNotificationStyleUpdate: false,
  enableSecureConnect: true,
  enableToneCook: true,
  toneDefault: 'Balanced',
  balTone: 'harmonyv3',
  crtTone: 'h3imaginative',
  prcTone: 'h3precise',
  enableSpeechChatDataAfterPhrase: false,
  enableSpeechEarconOnInput: false,
  enableSimpleVoiceInput: false,
  enableSpeechFateTTSStop: false,
  enableSpeechGetUserMedia: false,
  enableSpeechErrorHandling: false,
  enableSpeechTTSLatencyLogging: true,
  enableSpeechInputWhileRequestIsPending: false,
  enableSpeechIconDarkTheme: false,
  enableSpeechAriaLabel: false,
  enableSpeechReopenMic: false,
  enablePersistentToneSelector: false,
  enableBalDefault: true,
  enableNewTopicAutoExpand: true,
  enableTelemetryPrivacy: false,
  isAccountLinkedWithActiveAAD: false,
  enableThreadsAADMSASwitch: true,
  enableMaxTurnsPerConversation: true,
  // 以後台響應為準
  enableMaxTurnsFromBackend: true,
  maxTurnsPerConversation: 20,
  maxTurnsPerConversationMuidUser: 5,
  maxMessageLength: 4000,
  enableSigninTurnFix: true,
  enableAmberTurnPerConversation: false,
  amberTurnPerConversation: 0,
  enableAdSlugsDesktop: false,
  disResetTT: false,
  enablePerfTrk: true,
  enableTonePerf: true,
  enableSinglePerfEventPerMessage: true,
  enableEmbeddedPerf: false,
  enableAdSlugsMobile: true,
  enableCreatorShare: true,
  enablePuidOvr: false,
  enableUnauthRedir: true,
  enableSydSafeSearch: false,
  enableFeedbackClientSideScreenshot: false,
  enableAddMobileTagToCibOnShowConv: true,
  userPriorityLevel: 999,
  enableUserPriorityLevel: false,
  enableMMAnsType: true,
  enableStreamSyntheticTextResponses: true,
  enableToneCookExpiry: false,
  syntheticStreamSpeed: 55,
  disableShareWithNoMargin: false,
  enableMobileShareAnchorLeft: false,
  disableTabletScroll: false,
  disableTabletScrollOut: false,
  disableFocusedTabletScrollOut: false,
  disableTouchDesktopScroll: false,
  disableDesktopScroll: false,
  enableSuggEndFix: false,
  enableBalancedSerp: false,
  enableBalancedSerpLog: false,
  enableCreativeLandingPage: false,
  enableServerLogMerging: true,
  enableThreadShareWithoutRenderCardRequest: false,
  enableSuperOptionsSets: false,
  enableAutoRecoverFromInvalidSession: true,
  enableAutoRecoverFromInvalidSessionForFirstTurn: true,
  enableOneClickCopy: false,
  enableCodeCopy: true,
  enableRichTextPaste: true,
  enableInlineFeedback: false,
  enableInlineFeedbackV2: false,
  enableSerpFeedback: false,
  enablePersistentInputText: false,
  enableFeedbackMenuOverflow: false,
  enableActionBarIMEFix: true,
  shareLoadingUI: true,
  enableFeedbackInstrumentation: true,
  isSapphireClient: false,
  enableSydneySapphireUpsellMessageActions: false,
  enableSydneySapphireUpsellEndOfChat: false,
  enableSydneySapphireUpsellContinueConversation: false,
  sydneySapphireUpsellTreatment: 4,
  enableConvModeSwitchAjax: false,
  enableSetToneFromUrl: true,
  suppressKnobCreative: 0,
  suppressKnobBalanced: 0,
  suppressKnobPrecise: 0,
  enableSuppressTones: false,
  enableSearchQueryForInlineAds: false,
  enableDevFormOverrideForAds: false,
  enableMessageExport: true,
  enableFlatActionBar: true,
  codexMUIDUser: false,
  enableCodexMuidConsentTop: false,
  enableCodexMuidConsentExplicit: false,
  enableCodexMuidConsentImplicit: false,
  enableFixCodeXAsBug: true,
  enableCreatorSendQueryWhenShowConvQuery: true,
  enableCodexWinBotMessage: false,
  enableCodexWin: false,
  enableThreads: true,
  enableThreadsCF: false,
  codexWinEnableCustomGreeting: false,
  codexWinGreetingCustomString: '',
  codexWinCurrentTurn: 0,
  enableSkipContentOriginCheck: false,
  enableMobileOneClickShare: false,
  enableMobileOneClickShareV2: true,
  enableShareQuestionWithResponse: true,
  enableShareQuestionTitlePrefix: false,
  enableShareInlineAdsIframe: true,
  enableScreenshotIgnoreOnCibSerp: true,
  enableStandaloneUtility: true,
  enableShareWholeThreadMockUp: false,
  enableThreadShareLandingPage: true,
  enableShareThreadWithNoCache: true,
  enableDisposeOrphanedHosts: false,
  enablePreserveTextFormat: true,
  disable2TSearchHistory: true,
  enableSydBeacon: false,
  enableShareOnHostMessage: false,
  enableSydneySapphireCameraBridge: false,
  enableVisualSearch: false,
  enableChatCoach: '',
  suppressAlsoTryWhenEnableSydCarousel: false,
  suppressPoleRSWhenEnableSydCarousel: false,
  disablePassBotGreetingInContext: true,
  enableHoverCardOnLearnMorePills: false,
  /** 聊天記錄啟用更多，可導出 */
  enableThreadContextMenu: true,
  enableCloudflareCaptcha: true,
  enableResizeObserverWithAnimationFrame: true,
  enableStartPromotion: false,
  enableKnowledgeCardImage: true,
  enableMobileKnowledgeCardOverlay: true,
  suppressPoleRecommendedSearchWhenEnableSydCarousel: true,
  enableCopyButtonInstrumented: true,
  enableWowCDSSurvey: false,
  enableMessageExportWithPlainText: true,
  enableMessageExportOnlineWord: false,
  enableMessageExportOnlineExcel: false,
  enableThreadExportOnlineWord: false,
  enableCopyHtml: false,
  enableExportPdfWithAnswerScreenshot: false,
  enableExportDocxWithAnswerScreenshot: false,
  enableGetChats: true,
  enableExportDocxWithFormat: false,
  enableThreadSync: true,
  enableCssSplitConvModeOnClick: false,
  enableFlux3P: false,
  enableDelayShowConvEvent: false,
  disableWelcomeScreen: false,
  enableWelcomeScreenV2: false,
  enableNewTables: false,
  codexTableVersion: 1,
  enableTestDailyLimit: false,
  enableTestTurnLimit: false,
  enableWebPageContextMessages: false,
  enableCodexPluginb: false,
  enableBICHistory: true,
  enable2TScreenshot: false,
  enableWelcomeScreenAIRolesV1ForMobile: false,
  enableNewAutoSuggestEndPoint: false,
  enableFixChatScopeActive: false,
  enableHideConvMode: false,
  enableLoadCIBFromCDN: false,
  enableRenderCardRequestIMSearchParams: false,
  enableCodexTesthooks: false,
  flux3PPluginList: '',
  EnableTypingIndicatorAnimation: false,
  TypingIndicatorAnimationDuration: 1000,
  enableMessagePrivacy: false,
  codexOptionsSetsList: [],
  enableSydSuperAppAnchoredScroll: false,
  enable2TQueryConfigsOnSerpLoad: false,
  isMobileHost: false,
};
_w['_sydThreads'] = { threads: [] };
_w['_sydConvTranslation'] = {
  actionBarPlaceholder: '有問題盡管問我...（Shift + Enter = 換行，"/" 觸發提示詞）',
  actionBarAriaLabel: '詢問必應',
  actionBarComposeButton: '新主題',
  actionBarNewChatButtonDesktop: '開始新聊天',
  actionBarNewChatButtonMobile: '新建聊天',
  actionBarOngoingConvPlaceholder: '鍵入消息',
  attachmentLoading: '正在加載附件',
  captchaTitle: '驗證身份',
  captchaDescription: '若要繼續，請在下圖中輸入字符。',
  captchaPlaceholder: '輸入字符...',
  captchaPlaceholderError: '抱歉，請重試。',
  next: '下一步',
  cancel: '取消',
  feedbackAccessed: '訪問時間',
  feedbackSource: '源: 與必應的對話，',
  feedbackShareConversationQuery: '什麽是新版必應?',
  messageLearnMore: '了解詳細信息:',
  letsChat: '我們聊天吧',
  pause: '暫停',
  play: '開始遊戲',
  speechFailedRecognitionError: '抱歉，我無法收聽你的聲音，因為語音服務器已關閉，請稍後再試。',
  speechListening: '我聽著呢...',
  speechLoading: '正在等待音頻...',
  speechMediaNotReachableError: '很抱歉，我無法收聽你的聲音，因為你沒有可用的麥克風。',
  speechNoPermissionError: '你需要啟用麥克風，我才能聽到你的聲音。',
  speechAudioPlaybackError: '出錯了。',
  stop: '停止',
  welcomeContainerPrivacyStatement: '隱私聲明',
  welcomeContainerUseTerms: '使用條款',
  welcomeMessageItemContent1: '我可以為我挑剔的只吃橙色食物的孩子做什麽飯?',
  welcomeMessageItemContent2: '銷量最高的 3 種寵物吸塵器有哪些優點和缺點?',
  welcomeMessageItemContent3: '以海盜的口吻寫一首關於外太空鱷魚的俳句',
  welcomeMessageItemTitle1: '🧐 提出覆雜問題',
  welcomeMessageItemTitle2: '🙌獲取更好的答案',
  welcomeMessageItemTitle3: '🎨 獲得創意靈感',
  welcomeMessageItemLabel4: '更多創意中的新增功能：',
  warmWelcomeTitle: '歡迎使用新必應',
  welcomeSubtitleText: '由 AI 支持的網頁版 Copilot',
  workToggleDescription: '以及你的結果包括哪些內容',
  feedbackFirstMessage: '非常抱歉沒有幫助到你。是否可以詳細說明你不喜歡的方面?',
  feedbackPromptMessage: '感謝提醒。請提供反饋，以便必應團隊可以查看。',
  feedbackPromptGiveFeedback: '提供反饋',
  feedbackPromptGiveFeedbackAriaLabel: '提供反饋',
  feedbackPromptReportAConcern: '報告問題',
  feedbackPromptPositive: '很高興你喜歡這個答案！',
  feedbackFormTitleText: '為什麽這不起作用？',
  feedbackFormInputDefaultText: '在此處添加更多詳細信息。為了幫助保護你的隱私，請不要填入你的姓名或電子郵件地址等個人信息。',
  feedbackFormLegalText: '是否有法律或政策問題？',
  feedbackFormReportAConcern: '報告問題',
  feedbackFormNotificationTitleText: '反饋已提交',
  feedbackFormNotificationBodyText: '感謝你幫助必應改進！',
  serpFeedbackFormTitleText: '請幫助我們改進體驗',
  serpFeedbackFormInputDefaultText: '在此處輸入反饋。為了幫助保護你的隱私，請不要填入你的姓名或電子郵件地址等個人信息。',
  serpFeedbackFormScreenshot: '包括此屏幕截圖',
  submit: '提交',
  metaInternalSearchQuery: '正在搜索: `{0}`',
  metaInternalLoaderMessage: '正在為你生成答案...',
  metaInternalImageLoaderMessage: '分析圖像',
  compliantMetaInternalLoaderMessage: '從 {0} 生成安全答案',
  messageSharedContent: '共享內容',
  clickToView: '單擊以查看',
  more: '更多',
  expand: '展開',
  welcomeTertiaryTitleText: '使用 AI 的強大功能從 Web 中查找答案、創建書面內容等。',
  actionBarTextInputAriaLabel: '詢問必應',
  seeMore: '查看更多',
  seeLess: '查看更少',
  raiSuggestions: '這是什麽?',
  actionBarStopStreamingAriaLabel: '停止流式傳輸',
  actionBarTextInputModeButtonAriaLabel: '文本輸入模式',
  actionBarSpeechInputModeButtonAriaLabel: '啟用語音輸入模式',
  actionBarSubmitButtonAriaLabel: '提交',
  actionBarCancelSpeechInputButtonAriaLabel: '取消語音輸入/讀出',
  actionBarEditModeButtonAriaLabel: '編輯模式',
  actionBarSpeechBtnStartListeningAriaLabel: '開始聆聽',
  actionBarSpeechBtnStopListeningAriaLabel: '停止偵聽',
  actionBarSpeechBtnStopReadoutAriaLabel: '停止讀出',
  feedbackLikeButtonAriaLabel: '點讚',
  feedbackDislikeButtonAriaLabel: '取消點讚',
  feedbackOffensiveButtonAriaLabel: '標記為冒犯性',
  feedbackCopyButtonAriaLabel: '覆制',
  feedbackExportButtonAriaLabel: '導出',
  feedbackExportPdfButtonAriaLabel: 'PDF',
  feedbackExportTextButtonAriaLabel: 'Text',
  feedbackExportWordButtonAriaLabel: 'Word',
  feedbackShareButtonAriaLabel: '共享',
  messageSentAriaLabelPrefix: '已發送電子郵件',
  messageReceivedAriaLabelPrefix: '已收到消息',
  messageAttributionsCollapseBtnAriaLabel: '折疊',
  newTopicGreet1: '謝謝你! 知道你什麽時候準備好繼續前進總是很有幫助的。我現在能為你回答什麽問題?',
  newTopicGreet2: '重新開始總是很棒。問我任何問題!',
  newTopicGreet3: '當然，我很樂意重新開始。我現在可以為你提供哪些幫助?',
  newTopicGreet4: '當然，我已準備好進行新的挑戰。我現在可以為你做什麽?',
  newTopicGreet5: '很好，讓我們來更改主題。你在想什麽?',
  newTopicGreet6: '不用擔心，我很高興嘗試一些新內容。我現在可以為你回答什麽問題?',
  newTopicGreet7: '好的，我準備好了！感謝重置。我們應該了解哪些內容？',
  newTopicGreet8: '感謝刷新！你有新的話題嗎？',
  newTopicGreet9: '明白了，讓我們重新開始。接下來應該討論什麽？',
  newTopicGreet10: '下一步！我可以為你做什麽？',
  newTopicGreet11: '好的，我已準備好新話題。我們應該一起了解哪些內容？',
  newTopicGreet12: '明白了，請繼續！感謝告訴我。我能提供什麽幫助？',
  newTopicSugg1: '教我一個新單詞',
  newTopicSugg2: '如何設定可實現的目標?',
  newTopicSugg3: '教我有關登月的信息',
  newTopicSugg4: '世界上最小的哺乳動物是什麽?',
  newTopicSugg5: '最深的海洋是哪個?',
  newTopicSugg6: '一年有多少小時?',
  newTopicSugg7: '我想學習一項新技能',
  newTopicSugg8: '讓我大笑',
  newTopicSugg9: '有什麽新聞?',
  newTopicSugg10: '給我看鼓舞人心的名言',
  newTopicSugg11: '給我說個笑話',
  newTopicSugg12: '我需要有關家庭作業的幫助',
  newTopicSugg13: '尋找非虛構作品',
  newTopicSugg14: '激勵我!',
  newTopicSugg15: '向我顯示食譜',
  newTopicSugg16: '如何創建預算?',
  newTopicSugg17: '教我一個新單詞',
  newTopicSugg18: '天氣如何?',
  newTopicSugg19: '我想學習一項新技能',
  newTopicSugg20: '宇宙是如何開始的?',
  newTopicSugg21: '為什麽人類需要睡眠?',
  newTopicSugg22: '如何制作蛋糕?',
  newTopicSugg23: '火烈鳥為何為粉色?',
  newTopicSugg24: '全息影像的工作原理是什麽?',
  newTopicSugg25: '金字塔是如何建成的?',
  newUserGreet: '嘿，你好！我是必應，除了簡單搜索之外，我還可以幫助你完成各種操作。你可以詢問我關於從家庭作業到歷史記錄到帽子的任何信息。你的想法是什麽？',
  newUserSugg1: '搜索運行狀況',
  newUserSugg2: '搜索電影',
  newUserSugg3: '創作歌曲',
  repeatUserGreet: '你好，你又回來了！很高興再次看到你。我今天能幫你做什麽？',
  repeatUserSugg1: '曲奇食譜',
  repeatUserSugg2: '你可以做什麽?',
  repeatUserSugg3: '告訴我一個事實',
  creativeGreet: '讓我們發揮創意吧！你是否在考慮某個主題，還是即興發揮？',
  balancedGreet: '很好，我還可以幫助你發現新事物並找到答案。我們首先應該做什麽？',
  preciseGreet: '你好，我來幫你查資料。首先請問我一個問題。',
  creativeSugg1: '告訴我一個關於小狗的故事',
  creativeSugg2: '給雷雨寫一封情書',
  creativeSugg3: '我可以為好友做些什麽？',
  balancedSugg1: '為我提供有關新愛好的想法',
  balancedSugg2: '給我個周末度假的主意',
  balancedSugg3: '我需要一些建議',
  preciseSugg1: '誰發明語言？',
  preciseSugg2: '為我編輯內容',
  preciseSugg3: '給我列出今晚晚餐的購物清單',
  close: '關閉',
  newTopicPrompt: '通過新主題，可以開始與必應就任何主題進行全新對話',
  typingIndicatorStopRespondingAriaLabel: '停止響應',
  canceling: '正在取消',
  welcomeLearnSegment0: '必應由 AI 提供支持，因此可能出現意外和錯誤。請確保核對事實，並',
  welcomeLearnSegment1: '讓我們一起學習。必應由 AI 提供支持，因此可能出現意外和錯誤。請確保核對事實，並 ',
  welcomeLearnSegment2: '共享反饋 ',
  welcomeLearnSegment3: '以便我們可以學習和改進!',
  welcomeLearnMessage: '讓我們一起學習。必應由 AI 提供支持，因此可能出現意外和錯誤。請確保核對事實，並 {0} 以便我們可以學習和改進！',
  welcomeLearnFeedbackSubstitute: '共享反饋',
  actionBarSuspendConvPlaceHolder: '已為掛起的帳戶禁用消息傳遞',
  notiReConnect: '出錯了。',
  notiChatEnd: '聊天主題已結束。',
  notiRestartChat: '在 {0} 小時內開始新主題',
  notificationAttemptingToReconnect: '正在嘗試重新連接...',
  notificationProcessing: '正在嘗試連接，請稍候',
  notificationLostConnection: '很抱歉，你的連接似乎已斷開。',
  notificationLostConnectionCta: '是否要嘗試重新連接？',
  sydneySapphireCopyToClipboardText: '已覆制到剪貼板。',
  sydneySapphireUpsellContent: '現在就獲取使用新 AI 驅動的必應應用程序吧!',
  sydneySapphireWelcomeText: '歡迎回來! 下面是此頁面的一些內容。',
  sydneySapphireConsentTitleText: '使用新必應提升瀏覽',
  sydneySapphireConsentMessageText: '允許 Microsoft 訪問你的瀏覽器 Web 內容，以便使用 AI 生成的摘要和新必應的熱點功能更好地個性化你的體驗。了解更多信息',
  sydneySapphireConsentConfirmText: '確認',
  sydneySapphireConsentDenyText: '拒絕',
  typingIndicatorStopStreamingAriaLabel: '停止流式傳輸',
  sydneyCarouselCollapse: '折疊',
  sydneyCarouselTitle: '最近的聊天主題',
  messageActionsCopy: '覆制',
  messageActionsCopying: '正在覆制',
  messageActionsCopied: '已覆制',
  messageActionsCopyError: '錯誤',
  messageActionsExportPdf: 'PDF',
  messageActionsExportText: 'Text',
  messageActionsExportWord: 'Word',
  messageActionsReport: '報告',
  tooltipPositive: '點讚',
  tooltipNegative: '取消點讚',
  tooltipShare: '共享',
  tooltipExport: '導出',
  tooltipMore: '更多',
  tooltipSendToPhone: '在手機上繼續',
  mobileUpsellMessage1: '掃描此 QR 碼以在移動必應應用上繼續此對話',
  mobileUpsellTitle1: '在手機上繼續',
  sydneySapphireUpsellConsentTitle: '是否繼續從桌面聊天?',
  sydneySapphireUpsellConsentMessage: '你在其他設備上有一個活動的必應聊天。是否要繼續此對話?',
  sydneySapphireUpsellConsentConfirm: '是',
  sydneySapphireUpsellConsentDeny: '不，謝謝',
  actionBarAutoSuggestTab: '選項卡',
  actionBarAutoSuggestTap: '點擊',
  actionBarKeyboardHint: '輸入',
  feedbackShareAnswer: '查看此必應答案',
  feedbackShareGenerated: '查看我使用必應生成的內容',
  feedbackShareTitleFormat: '{0} | {1}',
  serpfeedback: '反饋',
  shareConversation: '共享整個對話',
  speechAuthenticationError: '身份驗證失敗。請稍後重試。',
  speechUnknownError: '出錯了。',
  refresh: '刷新',
  feedbackShareContent: '下面是我使用新的必應（全球首個 AI支持的應答引擎）生成的答案。單擊可查看完整答案，然後請你也來試一試。',
  preview: '預覽',
  toneSelectorDescription: '選擇對話樣式',
  toneSelectorCreative: '有創造力',
  toneSelectorCreativeModifier: '更',
  toneSelectorBalanced: '平衡',
  toneSelectorBalancedModifier: '更',
  toneSelectorPrecise: '精確',
  toneSelectorPreciseModifier: '更',
  toneSelectorMoreCreative: '更\\r\\n有創造力',
  toneSelectorMoreBalanced: '更\\r\\n平衡',
  toneSelectorMorePrecise: '更\\r\\n精確',
  notificationMaxTurnsPerDay: '很抱歉，你已達到可在 24 小時內發送到必應的郵件限制。請稍後回來查看!',
  notificationMaxTurnsPerConversation: '很抱歉，此對話已達到其限制。使用“掃除”按鈕清除此內容並進行更多聊天。',
  notificationMaxTurnsForMuidUsers: '你已達到今天的對話限制。',
  notificationUnauthorizedMuidUsersCta: '登錄以繼續你的聊天。',
  notificationChatEnterMuidUsers: '登錄以提出更多問題並進行更長的對話。',
  muidUsersTermsCond1: '通過單擊“開始使用”，並繼續與必應交互，即表示你接受',
  muidUsersTermsCond1Inline: '通過繼續與必應交互，你將接受 ',
  muidUsersTermsCond2: '並確認你已查看',
  muidUserGetStartedText: '開始使用',
  welcomeMobSugg1: '必應如何使用 AI?',
  welcomeMobSugg2: '必應還可以做什麽？',
  welcomeMobSugg3: '科技領域的最新消息是什麽？',
  of: '共',
  notificationResetConversation: '很抱歉，似乎出現錯誤。',
  notificationResetConversationCta: '讓我們重新開始吧。',
  toneSelectorCreativeTooltip: '清除對話並開始原創和富有想象力的聊天',
  toneSelectorBalancedTooltip: '清除對話並開始一個信息豐富且友好的聊天',
  toneSelectorPreciseTooltip: '清除對話並開始簡潔直截了當的聊天',
  toneSelectorSuppressedTooltip: '暫時不可用。請稍後再試!',
  notificationDisengaged: '也許該換個新話題了。',
  notificationDisengagedCta: '',
  notificationForbidden: '很抱歉，你似乎不再有權訪問此功能。請幾天後再次查看。',
  notificationTooManyRequests: '很抱歉，現在需求量非常大。請稍後重試。',
  notificationUnauthorized: '很抱歉，你似乎已注銷。',
  notificationUnauthorizedCta: '請重新登錄。',
  notificationMessageError: '上一條消息似乎已中斷。',
  notificationSharedTip: '此對話\u003cstrong\u003e“{0}”\u003c/strong\u003e已於 {1} 與你共享',
  mmAnswerPrompt1: '我總算給你找到了一些東西! 看一看。',
  mmAnswerPrompt2: '我終於找到了一些東西! 這是你要找的嗎?',
  mmAnswerPrompt3: '抱歉搞混了，我確實給你找到了一些東西。給你!',
  mmAnswerPrompt4: '嘿! 我確實找到了一些東西，這是你想要的嗎?',
  mmAnswerPrompt5: '看! 我找到了一些適合你的內容。',
  mmAnswerPrompt6: '等等，在這里! 抱歉弄亂了，看一下吧。',
  mmAnswerPrompt7: '我找到你要的媒體了! 抱歉耽擱了。',
  signInCta: '登錄 ',
  signInDescription: ' 以提出更多問題並進行更長的對話',
  exportSuccessToastTitle: '已導出文件。某些格式和圖像可能無法導出。',
  exportLoadingToastTitle: '正在導出...',
  exportedFileUserTitle: '用戶',
  exportedFileBotTitle: '必應',
  copyCodeSuccessToastTitle: '已覆制到剪貼板',
  copyCodeButtonTooltip: '覆制',
  copyCodeButtonSuccessTooltip: '已覆制',
  threadsSharedOnDate: '於 {0} 共享',
  threadsMore: '更多',
  threadsExportPanelTitle: '選擇格式',
  threadsExportPanelAriaLabel: '選擇',
  threadsAADMSARedirectConfirm: '切換用戶配置',
  threadsAADMSARedirectDescription: '正在使用 Microsoft 帳戶保存你的對話歷史記錄。下次使用個人帳戶登錄時，它將在此處顯示。',
  threadsCancel: '取消',
  threadsChatHistory: '聊天記錄',
  threadsConfirm: '確認',
  threadsDaysAgo: '{0} 天前',
  threadsDefaultChatName: '無標題的聊天',
  threadsDelete: '刪除',
  threadsDescription: '你的必應 AI 支持的 copilot 現可自動保存聊天功能。可以從任何設備、桌面或移動設備訪問聊天，並無縫恢覆。',
  threadsDescriptionNote: '請注意，除非專門保存，否則所有聊天將在 90 天內自動刪除。',
  threadsEdit: '重命名',
  threadsLoad: '加載聊天',
  threadsMinimizeRecent: '最小化最近的聊天',
  threadsMinimizeSaved: '最小化保存的聊天',
  threadsPreview: '預覽',
  threadsPreviewText: '跳回最近聊天',
  threadsRecentTitle: '聊天記錄',
  threadsRecentTitleShort: '最近使用',
  threadsSavedTitle: '已保存',
  threadsSeeAllRecent: '查看所有最近的聊天',
  threadsSeeAllSaved: '查看所有保存的聊天',
  threadsTitle: '聊天',
  threadsYesterday: '昨天',
  threads2TLastAccessed: '上次應答時間',
  threads2TInfoChanged: '此信息可能已更改，因為',
  threads2TArchivedText: '屏幕截圖',
  threads2TReloadDescription: '單擊“重新加載”以顯示來自 Web 的最新信息',
  threads2TFailedSearch: '請參閱最新 Bing.com',
  threads2TReload: '搜索 Bing.com',
  webPageContextPrefix: '已訪問網站',
  zeroInputSuggestionFallback1: '哪款咖啡研磨機評價最好？',
  zeroInputSuggestionFallback2: '對於一個預算有限的六口之家來說，會首選哪三款車型？',
  zeroInputSuggestionFallback3: '寫一個我的同事會覺得有趣的笑話',
  zeroInputSuggestionFallback4: '下一流行趨勢是什麽？我應該在哪里購物可以找到它？',
  zeroInputSuggestionFallback5: '撰寫關於魚和青蛙尋找愛的原創寓言故事',
  zeroInputSuggestionFallback6: '創建一個表，幫助我計劃接下來兩周的就餐',
  zeroInputSuggestionFallback7: '為具有諷刺風格的新社交媒體平台創建一個口號',
  zeroInputSuggestionCategory1: '商店',
  zeroInputSuggestionCategory2: '比較',
  zeroInputSuggestionCategory3: '大笑',
  zeroInputSuggestionCategory4: '聊天',
  zeroInputSuggestionCategory5: '寫入',
  zeroInputSuggestionCategory6: '組織',
  zeroInputSuggestionCategory7: '創建',
  discoverMessageItemTitle: '📝 一起重寫文本',
  discoverMessageItemContent: '嘗試從頁面中選擇文本以查看我們可以一起執行的操作',
  pluginTitle: 'Plugins',
  visualSearchFlyoutTitle: '添加圖像',
  visualSearchGenericErrorMessage: '很抱歉 - 你的上傳似乎有一次失敗。請重試',
  VisualSearchInvalidUrlMessage: '抱歉 - 你提供的 URL 似乎無效。請重試',
  visualSearchFlyoutInputboxAriaLabel: '粘貼圖像 URL',
  VisualSearchFlyoutTakePhotoButtonLabel: '拍照',
  visualSearchDragAndDropLabel: '“將圖片拖至此處',
  visualSearchFlyoutUploadButtonLabel: '從此設備上傳',
};
function parseQueryParamsFromQuery(n, t) {
  var u, f, e, o;
  t === void 0 && (t = !0);
  var r = [],
    s = n && n.length > 0 ? n.split('&') : [],
    h = s.length,
    i = null;
  for (u = 0; u < h; u++)
    (f = s[u]), (e = f.indexOf('=')), e > 0 && ((i = f.substr(0, e)), i.charAt(0) == '?' && (i = i.substr(1)), i && ((i = i.toLowerCase()), (r[i] = f.substr(e + 1))));
  return t && ((o = r.first), (r.first = null == o || o == '0' ? 1 : parseInt(o))), r;
}
function parseQueryParams() {
  var n = '';
  return (
    (n = typeof Bing != 'undefined' && Bing.Url && Bing.Location ? Bing.Url.getQueryString(Bing.Location.get()) : _w.location.search.substring(1)), parseQueryParamsFromQuery(n)
  );
}
function convertQueryParamsToUrlStr(n, t) {
  t === void 0 && (t = null);
  var i = t ? t : _w.location.pathname.replace(/^\/+/, '/');
  return i + '?' + queryParamsToString(n);
}
function queryParamsToString(n) {
  for (var e, o, r, u, s, f, t = [], i = 1; i < arguments.length; i++) t[i - 1] = arguments[i];
  if (((e = []), (u = t.length), u == 0)) for (s in n) n.hasOwnProperty(s) && (t.push(s), u++);
  for (f = 0; f < u; f++) (o = t[f]), (r = n[o]), (r || r === 0) && e.push(o + '=' + r);
  return e.join('&');
}
function getCurrentQuery() {
  if (!currentQuery) {
    var n = parseQueryParams();
    currentQuery = n.q;
  }
  return currentQuery;
}
function extractDomainFromUrl(n, t, i) {
  var r, u, f, e;
  return typeof n != 'string'
    ? null
    : ((r = n),
      (u = r.indexOf('://')),
      u >= 0 && !t && ((r = r.substr(u + 3)), (u = -1)),
      (u = u >= 0 ? u + 3 : 0),
      (f = r.indexOf(':', u)),
      f >= 0 && (r = r.substr(0, f)),
      (f = r.indexOf('/', u)),
      f >= 0 && (r = r.substr(0, f)),
      (e = i ? r.indexOf('www.') : -1),
      e >= 0 && (r = r.substr(u + 4)),
      r);
}
function addCommonPersistedParams(n) {
  var i = parseQueryParams(),
    t = queryParamsToString(
      i,
      'atlahostname',
      'cdghostname',
      'thhostname',
      'testhooks',
      'adlt',
      'akamaithumb',
      'safesearch',
      'perf',
      'mockimages',
      'mobile',
      'anid',
      'isuserauth',
      'uncrunched',
      'clientid',
      'currentdate',
      'iss'
    ),
    r = n.indexOf('?') === -1 ? '?' : '&';
  return (t = t.length > 0 ? r + t : ''), n + t;
}
var currentQuery = null;
var fab_config = { fabStyle: 1, fabSbAction: 'FocusSearchBox', fabSbActionHover: 'None', fabSbActionData: 'None', fabTooltip: '', micFabAlwaysVisible: false, fabClickNoAS: false };
sj_be(
  _w,
  'click',
  function () {
    _G.UIWP = true;
  },
  1
);
